---
title: "Final Project"
author: "Zhengtao Xu, Jennings Cheng and Collin Carmichael"
date: "7/22/2021"

output:
  pdf_document: 
    latex_engine: xelatex
    keep_tex: yes
  html_document: default
---


**Introduction**

**Exploratory Data Analysis**


```{r include=FALSE}
library(lars)
library(sm)
library(leaps)
library(stats)
library(pls)
library("tidyverse")
library("lubridate")
library("ggplot2")
library(dplyr)
library(faraway)
library(lmtest)
library(nlme)
```

```{r include=FALSE}
#Read and check data
Pollution<-read.csv("Final Project Data.csv",header=TRUE)
head(Pollution)
names(Pollution)
summary(Pollution)
# Change TEMP and PRES as numeric
Pollution$TEMP<-as.numeric(Pollution$TEMP)
Pollution$PRES<-as.numeric(Pollution$PRES)
summary(Pollution)
#Create date-time column for hourly data
Pollution$Date_H=with(Pollution, ymd_h(paste(Year, Month, Day, Hour, sep= ' ')))
#Create date column for daily data
Pollution$Date_D=with(Pollution, ymd(paste(Year, Month, Day)))
Pollution[1:5,]
#Hourly Plots
Pollution %>% 
  ggplot(aes(Date_H,PM2.5))+ geom_line()
# Build Daily data
Pollution_Daily<-Pollution %>%
  group_by(Date_D) %>%
  summarise(
  Avg_Day_PM2.5=mean(PM2.5,na.rm=TRUE),
  Avg_Day_DEWP=mean(DEWP,na.rm=TRUE),
  Avg_Day_TEMP=mean(TEMP,na.rm=TRUE),
  Avg_Day_PRES=mean(PRES,na.rm=TRUE),
  Max_Day_LWS=max(LWS,na.rm=TRUE),
  Max_Day_LS=max(LS,na.rm=TRUE),
  Max_Day_LR=max(LR,na.rm=TRUE),
  Max_Day_CBWD=nth(CBWD,which.max(LWS)))
# Convert Daily table to a data frame
Pollution_Daily=as.data.frame(Pollution_Daily)
# Check data structure and data summary
str(Pollution_Daily)
summary(Pollution_Daily)
# Daily Plots
 ggplot(Pollution_Daily, aes(Date_D, Avg_Day_PM2.5)) +
  geom_line()
 ggplot(Pollution_Daily, aes(Date_D, Avg_Day_DEWP)) +
  geom_line() 
ggplot(Pollution_Daily, aes(Date_D, Avg_Day_TEMP)) +
  geom_line()
ggplot(Pollution_Daily, aes(Date_D, Avg_Day_PRES)) +
  geom_line()
ggplot(Pollution_Daily, aes(Date_D, Max_Day_LWS)) +
  geom_line()
ggplot(Pollution_Daily, aes(Date_D, Max_Day_LS)) +
  geom_line()
ggplot(Pollution_Daily, aes(Date_D, Max_Day_LR)) +
  geom_line()
#Use functions year, month and day to create Year, Month and Day Columns
Pollution_Daily$Year=year(Pollution_Daily$Date_D)
Pollution_Daily$Month=month(Pollution_Daily$Date_D)
Pollution_Daily$Day=day(Pollution_Daily$Date_D)
head(Pollution_Daily)
#Fix NaN values in PM2.5 and set to NAs
Pollution_Daily$Avg_Day_PM2.5[is.nan(Pollution_Daily$Avg_Day_PM2.5)]<-NA
Pollution_Daily
#Train test
Pollution_Daily.test=Pollution_Daily[seq(1,nrow(Pollution_Daily),5), ]
Pollution_Daily.train = Pollution_Daily[-seq(1, nrow(Pollution_Daily) , 5 ) , ]
Pollution_Daily.test


```
```{r echo=FALSE}
Pollution_Daily_nona<-na.omit(Pollution_Daily)
keeps<-c("Avg_Day_PM2.5",'Avg_Day_DEWP','Avg_Day_TEMP','Avg_Day_PRES','Max_Day_LWS' , 'Avg_Day_PRES' 
         , 'Max_Day_LWS' , 'Max_Day_LS' , 'Max_Day_LR')
keeper=Pollution_Daily_nona[keeps]

cor(keeper)
```
```{r , echo = FALSE }
##Fitting Full Model
lm_all=lm(Avg_Day_PM2.5~.,data=Pollution_Daily.train)
testpm=predict(lm_all , Pollution_Daily.test)

summary(lm_all)
plot(c(1:366) ,  testpm , type = "l" , lwd= "2" , col = "red" )
lines( c(1:366),Pollution_Daily.test[,2])
Sys.setenv(LANG = "EN")

```

```{r include=FALSE}
##Functions to make Diagnostics Easier
test_error_assumptions<-function(x){
  b=bptest(x)$p.value
  c=shapiro.test(residuals(x))$p.value
  d=dwtest(x)$p.value
  a=data.frame("Homocedasticity",b>0.05,"Normality",c>0.05,"Uncorrelated Errors",d>0.05)
  return(a)
}

bptest(lm_all)
test_leverage<-function(x){
n=nrow(model.matrix(x)); p=ncol(model.matrix(x));
lev=influence(x)$hat
a=lev[lev>2*p/n]
  return(a)
}
ncol(model.matrix(lm_all))
test_outlier<-function(x){
  n=nrow(model.matrix(x)); p=ncol(model.matrix(x));
  jack=rstudent(x)
  b=jack[abs(jack)>abs(qt(.05/(2*n), n-p-1))]
  c=abs(qt(.05/(2*n), n-p-1))
  d=">"
  a=data.frame(b,d,c)
  return(a)
}
test_influence<-function(x){
  cook=cooks.distance(x)
  b=cook[cook>1]
  a=data.frame(b)
  return(a)
}
```

```{r echo = FALSE }
par(mfrow=c(2,2))
plot(lm_all)
```

```{r}
test_error_assumptions(lm_all)
```

```{r}
test_influence(lm_all)
```

```{r}
test_leverage(lm_all)
```

```{r}
test_outlier(lm_all)

```

```{r}
##Checking Interaction Term Significance
anova(lm_all)

```